Resolves #8 Player Controlled Character
johnying7/Five-Minute-Puzzle pull request #14
Opened 2020-03-21 14:47 UTC by johnying7

Resolves #8 Player Controlled Character

Character Prefab is in the Prefabs folder along with an extra scene camera (you can use the default main camera).

2020-03-22 08:10 UTC, taggartdev requested changes
I agree with the idea of scrapping Issue #9. I've updated Issue #8, with added criterion:
> -Top Down Camera View, locked to player's position, does not rotate with player.

I could not find an extra scene camera, only the Main Camera. The main camera works fine, save for the fact that it rotates with the player. 

Once the camera is locked to the player's movement, this should be good to resolve both Issues #8 and #9.

2020-03-24 17:12 UTC, johnying7 commented
the extra scene camera is in the prefabs folder. it's the same as a main camera so it won't matter in this case, but in future instances where I may have done something to the camera or set a reference, using set up prefabs is best practice. With the new camera system feedback, I will update this branch.

2020-05-03 17:52 UTC, taggartdev approved these changes

2020-05-03 17:53 UTC, taggartdev approved these changes

2020-05-04 04:10 UTC, merged